[package]
name = "fidget-ts"
version = "0.1.0"
authors = ["Steve Genoud <steve@sgenoud.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4"
fidget.workspace = true
gpu_interp = { path = "../../crates/gpu_interp" }
log = "0.4.22"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

console_log = { version = "1.0.0", features = ["wasm-bindgen"]}

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
