[package]
name = "fidget-ts"
version = "0.1.0"
authors = ["Steve Genoud <steve@sgenoud.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4"
getrandom = { version = "0.3", features = ["wasm_js"] }
fidget = {git = "https://github.com/mkeeter/fidget", tag="v0.3.5"}
log = "0.4.22"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

console_log = { version = "1.0.0", features = ["wasm-bindgen"]}

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

# We need to select a getrandom backend otherwise compilation targetting wasm fails.
#
# See:
# - Fidget's PR updating its getrandom dependency: https://github.com/mkeeter/fidget/pull/270
# - Fidget v0.3.5 release notes: https://github.com/mkeeter/fidget/releases/tag/v0.3.5
# - getrandom doc about this: https://docs.rs/getrandom/latest/getrandom/#webassembly-support
#
[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
