---
# This workflow automatically checks for errors in `packages/ui`
name: ui

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build fidget
        run: |
          cargo install wasm-pack
          cd packages/fidget
          npm install
          npm run build
      - name: Build sketch
        run: |
          cd packages/sketch
          npm install
          npm run build
      - name: Build draw-api
        run: |
          cd packages/draw-api
          npm install
          npm run build
      - name: Install
        run: |
          cd packages/ui
          npm install
      - name: Lint
        run: |
          cd packages/ui
          npm run lint
      - name: Typecheck
        run: |
          cd packages/ui
          npm run typecheck
